AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - time_frame.gemspec
    - Guardfile
    - 'vendor/**/*'
    - 'spec/models/vogon_poem.rb'

MinMax:
  Enabled: false

BlockLength:
  Enabled: false

# Setting the line length to a maximum of 80 chars.
LineLength:
  Enabled: true
  Max: 80

# Disabling the regex checks for now, since it fails with some generated gemspec
# lines.
RegexpLiteral:
  Enabled: false
